### ISSUE TITLE
NoCacheEntryException in case of scheduling a cache entry

### ISSUE THREAD

**Issue by DominikHerold** [jamesmh/coravel#111]
**Describe the bug**
I'm using following code:
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, IServiceProvider provider)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseMvc();
            var cache = provider.GetService<ICache>();
            cache.Remember("foo", BigDataLocalFunction, TimeSpan.FromSeconds(10));
            provider.UseScheduler(scheduler => scheduler.Schedule(() => cache.Remember("foo", BigDataLocalFunction, TimeSpan.FromSeconds(10))).EveryFiveSeconds().PreventOverlapping("test"));
        }

        private static int Counter = 0;

        private int BigDataLocalFunction()
        {
            return ++Counter;
        }
```
Which means my cache entry is valid for 10 seconds, but with a scheduler which runs every 5 seconds the cache entry is updated.

When accessing the cache via `return await _cache.GetAsync<int>("foo");` in a Controller method I sometimes receive a `NoCacheEntryException` anyway.

**Affected Coravel Feature**
I'm using version `3.0.0` of Coravel and it affects Scheduling and Caching.

**Expected behaviour**
When setting expire time of a cache entry higher than a scheduler timespan, I would not expect an `NoCacheEntryException`, but I would expect a correct result. The `GetAsync` method should everytime return a valid result seamlessly.
In general I want to invalidate my cache after a particular timespan. But even if it is invalid, it should return at least the old value until it is refreshed with a new value (by for example the scheduler).

**Comment by jamesmh** [comment]
The `NoCacheEntryException` would be expected in some cases. The scheduler runs using a cron kind of implementation, so if your scheduler is set to run every 5 seconds then it will run on a time like "1:00:05" or "1:10:15" - not necessarily 5 seconds from when the app starts.

The cache, on the other hand, uses a mere timer that could start at any moment.

So you could run into a case where the cache expires at "1:00:01" - leaving the cache invalidated for another 4 seconds until "1:00:05" when the scheduled task kicks in.

Under the covers, Coravel Cache is a wrapper for the built-in `IMemoryCache` in-memory .NET Core cache (which I can't change).

All that to say, using both the scheduler and cache this way isn't going to work for what you need.

We could expose a way for you to register a callback function when the cache entry expires - but still this might allow some very small cases where this would happen (e.g. just before the callback is completed, another thread tries to read the cache). Again, not sure how this is implemented by the .NET Core in-memory cache.

Otherwise, your best bet is probably to create your own method to do this:

```c#
public async Task<int> GetMyFoo()
{
     try 
     {
          return await _cache.GetAsync<int>("foo");
     }
     catch(NoCacheEntryException)
    {
         return cache.Remember("foo", BigDataLocalFunction, TimeSpan.FromSeconds(10));
    }
}
```

Of course, that could be generalized a bit more if needed? 

Also, you might need to lock or mutex to make sure only one thread is ever going to update the cache if you're looking for a super robust implementation?

**Comment by jamesmh** [comment]
Ah found it: https://github.com/jamesmh/coravel/blob/689e30d363f96420436a33dd62c768619aed796c/Src/Coravel/Cache/InMemoryCache.cs#L24

It's because calling `Remember` doesn't actually update the cached value. I think this is a bug...will have to think about it...but it does seem like one lol.

**Comment by jamesmh** [comment]
BTW, found it using this quick debug hack:

```c#
            var cache = app.ApplicationServices.GetService<ICache>();
            cache.Remember("foo", BigDataLocalFunction, TimeSpan.FromSeconds(10));
            app.ApplicationServices.UseScheduler(scheduler =>
            {
                scheduler.Schedule(() => {
                    Console.WriteLine("writing to cache at " + DateTime.UtcNow.ToString());
                     cache.Remember("foo", BigDataLocalFunction, TimeSpan.FromSeconds(10));
                }).EveryFiveSeconds().PreventOverlapping("test");

                scheduler.Schedule(async () =>
                {
                    try
                    {
                        Console.WriteLine("cache is " + (await cache.GetAsync<int>("foo")).ToString() + " at " + DateTime.UtcNow.ToString());
                    }
                    catch (Exception)
                    {
                        Console.WriteLine("cache is empty at " + DateTime.UtcNow.ToString());
                    }
                }).EverySecond().PreventOverlapping("test2");
            });
```

Which gave me:

![image](https://user-images.githubusercontent.com/7213174/66091852-df266500-e55f-11e9-93fa-415e4bc35d8c.png)

**Comment by DominikHerold** [comment]
So if I understood correct, this issue could be solved by allowing to update the cached item even it is not expired yet?

**Comment by jamesmh** [comment]
Exactly. For now, in your code, whenever your scheduled task runs you can call `cache.Forget("foo")` first, and then `Remember`.

Now that I'm thinking of it, the usage of `Remember` is that it does return the cached value when called, but by design will only will re-fill the cache if the key was expired. That's why using `GetAsync` and `HasAsync` together is recommended in the docs.

So I think this isn't a bug in that sense...but the docs do need to be clearer than they are.

If you use `Forget` before calling `Remember` then it should work for you though 👍
