### ISSUE TITLE
"Consummation" delay

### ISSUE THREAD

**Issue by antoinebj** [jamesmh/coravel#114]
Ok this isn't a very serious issue.

I just stumbled upon this project while looking for a job queuing library, read the docs a bit and noticed "consummation delay".

You might want to check out the definition of [consummation](https://en.wikipedia.org/wiki/Consummation), and then use "consumption" instead 😉

Beware of the English language and its [false friends](https://en.wikipedia.org/wiki/False_friend)!

**Comment by jamesmh** [comment]
lol I agree that consume/consumption might be a more appropriate word. Consummation doesn't only mean sexual intercourse though, but historically means to [complete or finish something](https://www.dictionary.com/browse/consummate) (like a contract, or some obligation, etc.)

I do think consumption would be a better word due to the common definition of "consummate" not really being well known or even used much these (modern) days lol

Thanks for point that out!

**Comment by antoinebj** [comment]
Well, I feel embarrassed now, first because most dictionaries do give a second definition for consummation that doesn't relate to marriage specifically, and second because I wrongly assumed you were not a native English speaker (hence my mention of false friend, as it looked like a mistake that a latin-based language speaker could easily have made).
Also, consumption doesn't have the same meaning, so depending on what you meant, maybe you chose the better word.
Anyway it's of little importance, sorry for the distraction. I would just close the issue but since you assigned it I'll let you decide what to do with it.

**Comment by jamesmh** [comment]
Np 👌 I do like "consumption" better, but for the sake of not breaking the API at the moment will leave it.

Thanks for the help!
