### ISSUE TITLE
Add EveryMinutes like EverySeconds

### ISSUE THREAD

**Issue by 3than7** [jamesmh/coravel#138]
Hi
good morning
Thanks for your efforts but I have a question.

why there no EveryMinutes with fixable int like every Seconds
or why i can't add more then 60 sec in EverySeconds ?

thank you

**Comment by jamesmh** [comment]
The reason is to keep a simple and terse API.

If you need something not found in the [fluent API](https://docs.coravel.net/Scheduler/#intervals) then the Cron method will work for you.

Supported Cron intervals are listed in the documentation [here](https://docs.coravel.net/Scheduler/#cron-expressions)

**Comment by 3than7** [comment]
i did tried cron expression like this ( 0 */5 * ? * *  )
and it's throw an exception  Cron expression '0 */5 * ? * *' is malformed

**Comment by jamesmh** [comment]
See https://en.wikipedia.org/wiki/Cron#CRON_expression

`0 */5 * * *` should work.

**Comment by 3than7** [comment]
thank you man

**Comment by jamesmh** [comment]
👍🎉 Let me know if you need anything else 😊

**Comment by Myhindash** [comment]
Hi, 
I need to create a new schedule to be executed one time using the crone expression like 
"0 35 05 30 5 ? 2020" which means "At 05:35:00am, on the 30th day, in May, in 2020"

how can I do that with the Coravel

thanks
