### ISSUE TITLE
Validate SMTP connection

### ISSUE THREAD

**Issue by MathavanN** [jamesmh/coravel#176]
Need to validate SMTP connection without sending mail.
before add the mailer service to the host builder, validate the email user name and password. 

validation result can be used to write in the log file/stop the application.

**Comment by jamesmh** [comment]
I think this would be more of a specific use-case that you are needing. I don't think adding this as a feature in Coravel would be appropriate since this would be more of an issue with configuration in general.

For example, I'm using Coravel to send mail but am manually catching any errors and handling them appropriately.
