### ISSUE TITLE
Coravel on worker service ( windows service ).

### ISSUE THREAD

**Issue by edsilrbasadre** [jamesmh/coravel#205]
Hi,

I'm 2 weeks old C# and .Net environment developer. 😅

I would like to ask guidance of the current project that I'm building using your Coravel plugin.

I'm currently building a worker service ( windows service ) that will be installed on host machine of our client to do ETL process. 
( More on extraction of data )

```
 public class Worker : BackgroundService
    {
        private readonly ILogger<Worker> _logger;
        private readonly IScheduler _scheduler;

        public Worker(ILogger<Worker> logger, IAmazonSQS sqs, IScheduler scheduler)
        {
            _logger = logger;
            _scheduler = scheduler;
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);

            try
            {
                _scheduler
                   .Schedule<ExtractorJobScheduler>()
                   .Cron("* * * * *")
                   .Weekday();
            }
            catch (Exception e)
            {
                _logger.LogInformation("Catch by exception");
                _logger.LogError(e.Message);
            }

            /*
            while (!stoppingToken.IsCancellationRequested)
            {
               
            }
            */
        }
    }
```

My questions are:

1.  Is this a correct approach in incorporating your Coravel plugin in a background service?
     I'm thinking if I can just have that ExtractorJobScheduler instead of placing the scheduler inside the Worker class. It looks like 
     redundant already but using that scheduler outside it didn't work when I installed it as a service.
2.  The OnError only availabe on global, how can I use that if I'm calling it inside the ExecuteAsync?

I know this is so newbie questions but I hope you can help. Thanks!

**Comment by jamesmh** [comment]
1. No - the schedule is already a "background worker" itself. So the code that schedules the `ExtractorJobScheduler` should be in your Startup file.
2. You can use `OnError` and it should work. Otherwise, your invocable itself might want to catch exceptions.

Here's a sample of a worker service - that might help :)

https://github.com/jamesmh/coravel/tree/master/Samples/WorkerServiceScheduler

Let me if that works 👍

**Comment by edsilrbasadre** [comment]
@jamesmh Alright! I was able to follow it and it's now working. Thanks for the quick response. 

You're a MVP. 😀

**Comment by jamesmh** [comment]
Awesome!

**Comment by pbijvani** [comment]
Hi @jamesmh 

Do you have sample code for setting Coravel as windows service? Code you provided is only a service worker template code.

I am looking for something which can be hosted as windows service.

Below is my code for program.cs where I have configured Coravel, Also it is configured to use windows service which is captured under default Worker.cs.

![image](https://user-images.githubusercontent.com/13973546/226734272-fd3defab-ca51-4139-9c01-6218b51354c4.png)

Now, my windows service start and stop event are under worker class. How to integrate something like this with Coravel.

Start windows service : start Coraval  Invocables
Store windows service : stop Coraval Invocables

any specific sample available?

**Comment by jamesmh** [comment]
@pbijvani there's no sample code because a windows services is just a worker service.

If you follow [this tutorial you should be able to get this working.(https://learn.microsoft.com/en-us/dotnet/core/extensions/windows-service#rewrite-the-program-class). 

Keep in mind that Coravel configures the background worker for you so you don't need to create any background workers / `IHostedService` as you did in your sample.

So your code sample would need to add this to the `ConfigureServices()` method:

```csharp
services.AddWindowsService(options =>
{
    options.ServiceName = ".NET Joke Service";
});
```

And remove this (unless you want to have your own worker service for some other reason?):

```csharp
services.AddHostedService<Worker>();
```
