### ISSUE TITLE
Added Debug warning when running an asynchronous action synchronously with Schedule instead of ScheduleAsync.

### ISSUE THREAD

**Issue by papakaliati** [jamesmh/coravel#21]
Added Debug warning when running an asynchronous action synchronously with Schedule instead of ScheduleAsync.

Basically as an non intrusive way to enforce the following note:
**_Note, that you are able to register an async method when using Schedule() by mistake. Always use ScheduleAsync() when registering an async method._**

**Comment by jamesmh** [comment]
links to #20

**Comment by jamesmh** [comment]
I think I'm going to hold this idea off for now. I think having the documentation notate the issue is sufficient.

I understand it may be helpful in the event of an honest mistake, but at this point I'm not totally convinced that Coravel needs to hold the developer's hand this much.

I know you probably wanted to add a "small" feature to coravel, but right now I'm trying to keep it as lean as possible.

Let me know if you have any other ideas 👍
