### ISSUE TITLE
Notify task scheduler to stop and run again.

### ISSUE THREAD

**Issue by eebasadre20** [jamesmh/coravel#212]
Hi there, thanks for this wonderful project. As a beginner in .NET this really help me to implement a scheduling task.

I would like to ask if there's a way to notify a task scheduler to stop and run again. My use case is when there's new configuration I would like to inform the task scheduler to fetch the new configuration then process it. So I think it needs to stop first ( if there's a current job running ) and run it again.

Thanks!

**Comment by jamesmh** [comment]
Not at the moment. You'd have to stop the .NET process and bring it back up. Unless there's a way to hook into the .NET framework and "stop" all background worker services and restart them, but I'm not aware of whether that's possible or not.

**Comment by eebasadre20** [comment]
> Not at the moment. You'd have to stop the .NET process and bring it back up. Unless there's a way to hook into the .NET framework and "stop" all background worker services and restart them, but I'm not aware of whether that's possible or not.

Hi James, I really appreciate your fast reply. It looks like I didn't notice that you responded already 3 days ago.

Anyhow, what do you mean about to stop the .NET process and bring it back up? Is that the service?

**Comment by jamesmh** [comment]
You would need to restart the .NET application / process to re-build the schedules since everything is built at application start-up.

My comment about restarting the "worker service" is related to how Coravel is built internally. It's a [hosted service](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-5.0&tabs=visual-studio). I'm not aware of a way to "restart" hosted services.
