### ISSUE TITLE
Looking for advice on multi-tenant scheduling with Coravel

### ISSUE THREAD

**Issue by pkellner** [jamesmh/coravel#229]
My problem is that I have a single .net app that allows for multiple logged in users where each user has their own set of cron jobs.  Those users can get created after the server starts so all the needed jobs can not be launched a site start.

More specifically, for each user (could be thousands of them), I want to be able to dynamically stop and start processing of those cron jobs.  For example, for each user I want two separate jobs running, one that goes every 5 seconds and one that goes every 60 seconds.  I actually only want one or the other running so I want to be able to dynamically pause the 5 second while keeping the 60 second one running or, pause the 5 second and keep the 60 second going (I don't need to worry about the jobs going to completion at the time of pause).

Suggestions for how to make this happen?

**Comment by pkellner** [comment]
I think I have a plan.  I'll close for now.

**Comment by jamesmh** [comment]
Just saw you closed, but I'll post anyways. 

This isn't officially in the docs yet, but it's how Coravel Pro works (by dynamically creating schedules).

You can take a look at [this issue for some history](https://github.com/jamesmh/coravel/issues/219) if you want (not necessary). Others have asked about similar usages lol. 

Essentially, you can inject an `IScheduler` via DI wherever and use [any of the `IScheduler` methods to schedule](https://github.com/jamesmh/coravel/blob/master/Src/Coravel/Scheduling/Schedule/Interfaces/IScheduler.cs).

You can use the `PreventOverlapping` passing a unique Id (possibly a combination of userId, tentantId, jobname, etc.) to keep track of all the keys of scheduled jobs you've created. Internally, Coravel called another method `AssignUniqueIndentifier` which, if you want, you can cast the `IScheduleInterval` object to a `ScheduledEvent` type and call it directly (if you do want overlapping enable).

Later, you would use the id to unscheduled [using `TryUnschedule()` from the scheduler](https://github.com/jamesmh/coravel/blob/751d1c39fad0f65b8201d30b64a3b25053818e6d/Src/Coravel/Scheduling/Schedule/Scheduler.cs#L121).

So all in all, the `AssignUniqueIndentifier` and `TryUnschedule` are not exposed via the explicit interfaces. These methods were not exposed specifically because they were used by Coravel Pro and were kinda "hidden". But all it would take is for me to expose those methods for this to be "official".

So, you can try that if you want. If you do, let me know if that works - would love the feedback.

Just to call it out, these are all thread-safe methods and should work fine. For myself, I'd need to:

1. Expose these methods via the appropriate interface
2. Add some robust tests to the public project

So many have asked for this, so I think it makes sense to expose. My only concern is whether there's an even more user-friendly way to accomplish this - since I didn't build these methods for public use originally.

**Comment by jamesmh** [comment]
Actually, I do see an issue with the worker services that's not thread-safe (I'll need to fix that). But otherwise should be as I described.

**Comment by pkellner** [comment]
Thanks!  That's great insights.  

My thinking is to create just two scheduled jobs, one on 5 seconds, and one on 60 seconds.  

Have a flag column  in the user table saying which schedule any particular user is on, then in each job, iterate through all the users and launch each task asynchronous and wait in the task for them all to complete or timeout.  

I didn't mention that all the individual user tasks are IO heavy (they call a remote web service), so they are mostly waiting.  

I'm not sure if this or creating lots of schedules is better.

**Comment by jamesmh** [comment]
Your approach is generally what I think most people would do, since you have more control over your stuff.

You can choose, for example, to fetch 10 separate user jobs at once, initiate 10 concurrent I/O calls to APIs or whatever. Otherwise, creating a bunch of schedules would work but you don't have as much control over how the concurrency is going to work.

**Comment by pkellner** [comment]
I'm assuming you know this, but just in case not.  EF contexts are not thread safe.  https://docs.microsoft.com/en-us/ef/core/dbcontext-configuration/#avoiding-dbcontext-threading-issues

**Comment by jamesmh** [comment]
Yes, found this out the hard way not that long ago actually lol. I generally like using something like Dapper for views/queries since I can initiate multiple connections to perform concurrent fetches, etc.
