### ISSUE TITLE
Microsoft.AspNetCore.App dependency

### ISSUE THREAD

**Issue by IonRobu** [jamesmh/coravel#39]
Coravel package is dependent of Microsoft.AspNetCore.App. This is a problem for using package in business projects.

**Comment by IonRobu** [comment]
Maybe IApplicationBuilder extension methods from Registration classes should be rewritten as IServiceCollection or IServiceProvider extensions methods?

**Comment by jamesmh** [comment]
I'll do some investigation and get back to you. My initial thought is that the Application piece is needed due to the way the internal services are tied right into the DI container, which let's Coravel use DI etc.

I'll let you know. 

P.S. any specific feature that you need in a shared project?

Thanks!

**Comment by IonRobu** [comment]
The scenario is perfect in asp.net core applications, but the middle ("business") layer referring the Coravel package may be also used in non-web scenario, so I think the Microsoft.AspNetCore.App reference should not be there.

**Comment by jamesmh** [comment]
What pieces of Coravel would you use in that scenario?

**Comment by jamesmh** [comment]
I think converting to IServiceProvider might be promising. I def cannot use IServiceCollection since Coravel needs access to the provider to "rig" stuff up.

I'll let you know when I've got some more progress made 👍

**Comment by jamesmh** [comment]
This might also fix another concern I'm having with another piece I'm building...

Thanks for the feedback @IonRobu !

It's great having people able to give some more insight / alternative scenarios.

**Comment by jamesmh** [comment]
Playing around right now, here's the quick and dirty version.I removed the non-abstract dep. on AspNetCore and kept the very specific pieces I need - but using the appropriate "abstractions" reference. Here's what that would look like:

```
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="2.1.0"/>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="2.1.0"/>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="2.1.0"/>
```

Already, build times are extremely faster too since it's not bringing in that entire ecosystem.

So either way this is promising 👍 

What do you think about these dependencies?

**Comment by tthiery** [comment]
I can only agree with the other participants here and your solution. Queue-bound microservices e.g. do not rely on ASP.NET Core but for example its nice `IHostBuilder` component instead of the `IWebHostBuilder` interface. Also there is no `Startup` class in that case.
Other projects like `Serilog` utilize additional NuGet packages to create a more native feeling for dedicated frameworks like ASP.NET Core `Serilog.AspNetCore`.

Thanks for your work.

**Comment by IonRobu** [comment]
> Playing around right now, here's the quick and dirty version.I removed the non-abstract dep. on AspNetCore and kept the very specific pieces I need - but using the appropriate "abstractions" reference. Here's what that would look like:
> 
> ```
>     <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="2.1.0"/>
>     <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="2.1.0"/>
>     <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="2.1.0"/>
> ```
> Already, build times are extremely faster too since it's not bringing in that entire ecosystem.
> 
> So either way this is promising 
> 
> What do you think about these dependencies?

I think is very good. Also, @tthiery's proposed pattern is a good one - having a framework-specific "extension" packages

**Comment by jamesmh** [comment]
Great - thanks @tthiery  and @IonRobu  for the awesome feedback! I'll aim to publish the changes later today 👍

**Comment by jamesmh** [comment]
Coravel nuget 1.9.0 should be available. [Release Notes here](https://github.com/jamesmh/coravel/releases/tag/1.9)

Thanks @tthiery and @IonRobu ! Let me know how things work out.
