### ISSUE TITLE
Distributed Server

### ISSUE THREAD

**Issue by muhammetsahin** [jamesmh/coravel#7]
What should I do if I want the scheduler to run on a single server on distributed servers? Thank you.

**Comment by jamesmh** [comment]
At this point, you could choose to have a dedicated instance / server - but that may not be the best for you lol.

I'd like to build into Coravel some sort of distributed feature, but right now it doesn't exist. 

But, since Coravel is just code that you write (to configure your schedules), you could have an environment variable that only one of your distributed servers has assigned (let's say "USE_SCHEDULER"). In your code, you could do a check -> if "USE_SCHEDULER" is set and is "TRUE", then configure and run the scheduler. Otherwise, just bypass it.

Hopefully that helps for now :)

**Comment by muhammetsahin** [comment]
Thank you for your answer. Yes very helped  to me :)

**Comment by jamesmh** [comment]
Awesome! Let me know if you have any other suggestions etc.
