### ISSUE TITLE
Questions: A list of questions.

### ISSUE THREAD

**Issue by markalanevans** [jamesmh/coravel#79]
Hi, This project looks great! We are currently using Hangfire and it is pretty great, but it doesn't have the developers full attention, so metrics, reporting, and 3rd party integrations are not easy.

Just a few questions for:
- Can you have multiple queues: Default, Critical, Events, Email?
- I don't see any documentation about scale / workers? If I put 100,000 jobs in a queue, how does that get processed?

**Comment by jamesmh** [comment]
Thanks Mark!

Right now there's only one queue that is processed asynchronously (which is one thing that makes Coravel distinct from Hangfire. Hangfire doesn't support true async operations and will block on all I/O, etc.)

So, if you have, for example, 100,000 jobs in the queue - and they are I/O bound async operations, they will be executed (mostly) in parallel due to the nature of Coravel supporting async operations. For CPU bound operations, they will simply be executed sequentially one-by-one.

The reason the queue was done this way is that Coravel will always just use one thread from the thread pool. 

This is how the scheduler works too. However, I recently added a new feature called [schedule workers](https://github.com/jamesmh/coravel/blob/master/Docs/Scheduler.md#schedule-workers). This is basically what you would be looking for - but with the queue. It would just be a way to segment the queue into buckets where each bucket would have a dedicated thread to process it.

But, on the other hand, being able to assign multiple queues with their own priority and polling intervals would be nice...

A potential "new feature"?

**Comment by jamesmh** [comment]
Going to close for now, let me know if you have any concerns, questions, etc.?
